name: ogo
channels:
  - numerics88
  - defaults
  - conda-forge
dependencies:
  - aimio=1.0.0
  - boost=1.67.0
  - bzip2=1.0.8
  - c-ares=1.25.0
  - ca-certificates=2023.12.12
  - cftime=1.4.1
  - curl=8.5.0
  - expat=2.5.0
  - fftw=3.3.9
  - freetype=2.12.1
  - future=0.18.2
  - hdf4=4.2.15
  - hdf5=1.10.5
  - icu=58.2
  - jpeg=9e
  - jsoncpp=1.8.4
  - krb5=1.21.2
  - lerc=4.0.0
  - libblas=3.9.0
  - libboost=1.67.0
  - libcblas=3.9.0
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran5=13.2.0
  - libiconv=1.17
  - libitk=4.13.2
  - liblapack=3.9.0
  - libnetcdf=4.7.1
  - libnghttp2=1.58.0
  - libopenblas=0.3.25
  - libpng=1.6.39
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libtiff=4.4.0
  - libwebp-base=1.3.2
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.8.3
  - n88tools=9.0.0
  - n88util=2.0.0
  - ncurses=6.4
  - netcdf4=1.5.3
  - openssl=3.2.0
  - pip=23.3.2
  - pqctio=1.0.0
  - py-boost=1.67.0
  - python=3.7.12
  - python_abi=3.7
  - readline=8.2
  - scipy=1.6.1
  - setuptools=69.0.3
  - simpleitk=1.2.4
  - sqlite=3.44.2
  - tbb=2020.2
  - tk=8.6.13
  - vtk=8.2.0
  - vtkbone=1.1.0
  - wheel=0.42.0
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - anyio==3.7.1
      - appnope==0.1.3
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - attrs==23.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - cffi==1.15.1
      - comm==0.1.4
      - cycler==0.11.0
      - debugpy==1.7.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - entrypoints==0.4
      - exceptiongroup==1.2.0
      - fastjsonschema==2.19.1
      - fonttools==4.38.0
      - idna==3.6
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - ipykernel==6.16.2
      - ipython==7.34.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - jedi==0.19.1
      - jinja2==3.1.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==7.4.9
      - jupyter-console==6.6.3
      - jupyter-core==4.12.0
      - jupyter-server==1.24.0
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.9
      - k3d==2.16.1
      - kiwisolver==1.4.5
      - markupsafe==2.1.3
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - msgpack==1.0.5
      - nbclassic==1.0.0
      - nbclient==0.7.4
      - nbconvert==7.6.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.9
      - notebook==6.5.6
      - notebook-shim==0.2.3
      - numpy==1.21.6
      - packaging==23.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.43
      - psutil==5.9.7
      - ptyprocess==0.7.0
      - pycparser==2.21
      - pygments==2.17.2
      - pyparsing==3.1.1
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pyzmq==24.0.1
      - qtconsole==5.4.4
      - qtpy==2.4.1
      - send2trash==1.8.2
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - terminado==0.17.1
      - tinycss2==1.2.1
      - tornado==6.2
      - traitlets==5.9.0
      - traittypes==0.2.1
      - typing-extensions==4.7.1
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - widgetsnbextension==4.0.9
      - zipp==3.15.0