# This is a basic workflow to help you get started with Actions

name: Python CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    [cron: "0 12 1,15 * *"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: [3.7]
    
    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}
    
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          mamba-version: "*"
          activate-environment: test
          channels: numerics88,simpleitk,conda-forge
          auto-activate-base: false
      - uses: actions/cache@v3
        id: conda-env-cache
        with:
          path: ${{ env.CONDA }}/envs/test
          key: conda-env-${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('.github/workflows/main.yml') }}
      - name: Create and install dependencies
        if: steps.conda-env-cache.outputs.cache-hit != 'true'
        run: |
          mamba install -y -n test n88tools click flake8 matplotlib nose numpy opencv pandas pbr pytest scipy simpleitk six sphinx pydicom gdcm
      - name: Install package
        run: |
          conda activate test
          pip install -e .
      - name: Run tests
        run: |
          python -m pytest tests
